### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

### ISSUE THREAD

**Issue by aladdinsparta** [BlackArch/blackarch-site#128]
[aladdinx@aladdinx ~]$ sudo websploit
Traceback (most recent call last):
  File "/usr/bin/websploit", line 33, in <module>
    sys.exit(load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')())
  File "/usr/bin/websploit", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/websploit.py", line 3, in <module>
    from .core.utils import check_dependencies
  File "/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/core/utils/__init__.py", line 1, in <module>
    from .tools import *
  File "/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/core/utils/tools.py", line 1, in <module>
    from scapy.all import *
  File "/usr/lib/python3.9/site-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/usr/lib/python3.9/site-packages/scapy/arch/__init__.py", line 28, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3.9/site-packages/scapy/arch/bpf/core.py", line 31, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 330, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
[aladdinx@aladdinx ~]$

**Comment by dualfade** [comment]
Quick fix --
sudo ln -s -f /usr/lib64/libc.a /usr/lib64/liblibc.a

Looking into where this is coming from ??

**Comment by dualfade** [comment]
Looks like it is coming from here --
https://bugs.python.org/issue42580

In python 3.9 lib rename.

**Comment by aladdinsparta** [comment]
Thanks
